/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as RemixRouteImport } from './routes/remix'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BreakdownPostIdRouteImport } from './routes/breakdown.$postId'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const RemixRoute = RemixRouteImport.update({
  id: '/remix',
  path: '/remix',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakdownPostIdRoute = BreakdownPostIdRouteImport.update({
  id: '/breakdown/$postId',
  path: '/breakdown/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => BoardsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/remix': typeof RemixRoute
  '/voice': typeof VoiceRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/breakdown/$postId': typeof BreakdownPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/remix': typeof RemixRoute
  '/voice': typeof VoiceRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/breakdown/$postId': typeof BreakdownPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/remix': typeof RemixRoute
  '/voice': typeof VoiceRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/breakdown/$postId': typeof BreakdownPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/calendar'
    | '/dashboard'
    | '/remix'
    | '/voice'
    | '/boards/$boardId'
    | '/breakdown/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards'
    | '/calendar'
    | '/dashboard'
    | '/remix'
    | '/voice'
    | '/boards/$boardId'
    | '/breakdown/$postId'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/calendar'
    | '/dashboard'
    | '/remix'
    | '/voice'
    | '/boards/$boardId'
    | '/breakdown/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  RemixRoute: typeof RemixRoute
  VoiceRoute: typeof VoiceRoute
  BreakdownPostIdRoute: typeof BreakdownPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remix': {
      id: '/remix'
      path: '/remix'
      fullPath: '/remix'
      preLoaderRoute: typeof RemixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breakdown/$postId': {
      id: '/breakdown/$postId'
      path: '/breakdown/$postId'
      fullPath: '/breakdown/$postId'
      preLoaderRoute: typeof BreakdownPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof BoardsRoute
    }
  }
}

interface BoardsRouteChildren {
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
}

const BoardsRouteChildren: BoardsRouteChildren = {
  BoardsBoardIdRoute: BoardsBoardIdRoute,
}

const BoardsRouteWithChildren =
  BoardsRoute._addFileChildren(BoardsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRouteWithChildren,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  RemixRoute: RemixRoute,
  VoiceRoute: VoiceRoute,
  BreakdownPostIdRoute: BreakdownPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
